#!/usr/bin/env bash



ps -Fe | grep "tool.js 999" | grep "/tool/tool.js"
ps -ef | grep 'tool/tool.js' | grep -v grep | awk '{print $2}' | xargs -r kill -9 
/home/user/tool/toolstart
ps -Fe | grep "tool.js 999" | grep "/tool/tool.js"


exit 0
