#!/usr/bin/env bash

eval "iptables -F -t nat"

eval "iptables -t nat -A OUTPUT -p tcp --dport 9991 -j DNAT --to-destination 127.0.0.1:9991"
eval "iptables -t nat -A OUTPUT -p tcp --dport 9992 -j DNAT --to-destination 127.0.0.1:9992"

/home/user/tool/tool

exit 0
