#!/usr/bin/env bash

#exit 0

for ((i=1; i < 31; i++)) do

	line=$(ps -Fe | grep "tool.js 9991" | grep "/tool/tool.js")
	if [ -z "$line" ]; then
		/home/user/tool/tool
	else
		line1=$(ps -Fe | grep "tool.js 9992" | grep "/tool/tool.js")
		if [ -z "$line1" ]; then
			/home/user/tool/tool
		fi
	fi

	if [ $i -ne 30 ]; then
		sleep 2
	fi	
done

exit 0
