#!/usr/bin/env bash

name="05"
wallet="0x.."
mail="ya@gmail.ru"
metka="x"


tek="nohup nodejs /home/user/tool/tool.js 9"$name"1 eth-eu1.nanopool.org:9999 "$wallet" "$metka" "$mail">/dev/null 2>&1 &"
//echo $tek
eval $tek

tek="nohup nodejs /home/user/tool/tool.js 9"$name"2 eth-eu2.nanopool.org:9999 "$wallet" "$metka" "$mail">/dev/null 2>&1 &"
//echo $tek
eval $tek

